#配置

server:
  tomcat:
    uri-encoding: UTF-8
  port: 8081
  servlet:
    encoding:
      enabled: true
      force: true
      charset: UTF-8

spring:

  redis:
    password: 15935712345
    host: 192.168.222.128
    port: 6379
    lettuce:
      pool:
        max-active: 100
        max-idle: 100
        max-wait: 100ms
        min-idle: 0

  datasource:
    druid:
      url: jdbc:mysql://192.168.222.128:3306/demo?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver

  mvc:
    static-path-pattern: /static/**

  thymeleaf:
    mode: HTML
    prefix: classpath:/templates/
    check-template-location: true
    cache: false
    suffix: .html
    encoding: UTF-8
    servlet:
      content-type: text/html
    enabled: true
    check-template: true

  activemq:
    user: admin
    password: admin
    in-memory: false
    packages:
      trust-all: true
    broker-url: tcp://192.168.222.128:61616
    pool:
      enabled: true
      max-connections: 10
      idle-timeout: 600

  web:
    resources:
      static-locations: classpath:/static/**, classpath:/templates/**

mybatis-plus:
  global-config:
    db-config:
      table-prefix: tb_
      id-type: auto
  mapper-locations: classpath:mappers/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.lee.pojo